### PR TITLE
add protect to handle

### PR DESCRIPTION
**Pull request by fnwinter**
- add handle protect (ifdef/endif) for extensions

### CODE REVIEW

**Comment by fnwinter** [comment]
could we add protect to xr.xml like this?
        <type category="handle" parent="XrSession" protect="XR_MSFT_scene_understanding">
            <type>XR_DEFINE_HANDLE</type>(<name>XrSceneObserverMSFT</name>)</type>

**Comment by rpavlik** [comment]
Hmm. It's a "type" element, so I think so? I know it can be done for structs, so I'd assume you could also do it for handles, even though those are just little opaque typedefs on 64-bit and uint64_t typedefs on 32.

**Comment by rpavlik** [comment]
Ah, I didn't look closely at the protect value mentioned here. the "protect" on XR_MSFT_scene_understanding in other places is "automatic" - not from the XML.

**Review by rpavlik — APPROVED** [review]

**Comment by rpavlik** [comment]
Ah, it needed a change in the OpenXR scripts themselves. I've queued that up.

**Pull request merged**
