### PR TITLE
Working 1.0.30 build

### PR DESCRIPTION
**Pull request by jherico**
Fix several bugs blocking generation of valid C++ bindings

Targeting #39 as well as some other issues related to lines in the XR registry like this: 
```
        <type category="struct" name="XrDevicePcmSampleRateGetInfoFB" alias="XrDevicePcmSampleRateStateFB"/>
```

This _should_ generate a `using DevicePcmSampleRateStateFB = DevicePcmSampleRateGetInfoFB;` line in the structs file, but doesn't, so functions returning the `DevicePcmSampleRateStateFB` fail to compile.

### CODE REVIEW

**Comment by jherico** [comment]
@rpavlik These changes seem to produce a valid `openxr.hpp` file, at least on my system.  One that compiles without any compiler errors.  I haven't yet fully tested it and it contains at least one obvious hack.  Let me know if you have a better approach for `XrSpaceUserIdFB`.

**Comment by rpavlik** [comment]
Thanks for this great work! I cleaned it up a little more in places. I can't actually build the built in cmake project on 1.0.31 but I'll believe you if you say it works for 1.0.30.

**Comment by jherico** [comment]
Hmmm...  I'm actually working against the 1.0.31 version of xr.xml from [OpenXR-SDK-Source](https://github.com/KhronosGroup/OpenXR-SDK-Source/tree/5e9bc99c5e2e9d8873a83db58aec6ee63dd1f289) but I didn't see any error with that.  Let me try with your changes.

...

Nope... still able to compile files including `<openxr/openxr.hpp>` using 1.0.31 version of the `openxr.h` headers, and HPP files generated from the 1.0.31 version of `xr.xml`.  Might be a compiler difference... I'm using MSVC 2022.  I'll see if I can test this out with Clang & GCC later.

**Comment by jherico** [comment]
Ah, OK, I see... If I include this code it fails:

```
    xr::Instance i;
    xr::DispatchLoaderDynamic dispatch{ i };
    xr::PlaneDetectorEXT pd;
    auto x = pd.getPlaneDetectionStateEXT(dispatch);
```

And unless `PlaneDetectorEXT` was added in 1.0.31, it will probably fail on 1.0.30 as well.  My code doesn't comprehensively exercise all the functions and for MSVC at least, if the template isn't instantiated, it doesn't prevent compilation.  Let me see if I can resolve this.

**Comment by rpavlik** [comment]
OK I fixed it here.

**Comment by rpavlik** [comment]
I'll merge your stuff then my own fixes. Basically we were overriding the existing projection stuff if we decided to return something as the sole return value, which broke on returning an enum.

**Comment by rpavlik** [comment]
OK see #45 - take a look and see if it makes sense, then I'll merge that

**Comment by jherico** [comment]
#45 lgtm

**Pull request merged**
